language: java
jdk:
- openjdk8
before_install:
- chmod +x mvnw
script: "./mvnw clean install"
notifications:
  email: rodrigocallegaldos@gmail.com
deploy:
  app: upc-202102-sw61-sale-system-1
  provider: heroku
  api_key:
    secure: FoQGF5rjCLh5WI0vpwS+KDUs+QZX1WW83yjNOP38cYR2GGXluFtNZz3NuvrtfgkcfPg+z/8+24VG73AfpPvK1CneUuf5854JAysW7Tc/p/GKDU9re1IHqeeIdohE1aZU/7wj/RhSzMuWasPVpN0jawHfDsLQVnNjQKrFs+XdDo++l2xikCWYLoaAZFE56qI1IoU200yyyqHHLNPnxJTWaA1/yputq3+i9iviAUip/k9+1O4Yjepp0ypZ7P3gQXIoVhHLsOCIfhbSZ/DGXkC8chRgFTrukgyqRneaBd0Q9ybfERI/KOScv+hmslSz3UAVc9v3Tof9pF3qAyuiFYSQvvYH6s74njnLZR3AKWWSDChR778or1sFr5LAptj2POxaoBUZkihD3fRBGsFjrHQsiSjfczaOSRWqeaVdb1vLSTTs/jAOHJJ6l5inEvl2JFuggMItKOgkRRkTM85tbEuxCUSYA3u4IqhhpOID0TTrp+eSu60LyLZSd8q2INilIvz2xgXa9hdcArqXZ4gOgO9nZFytFhkNRwjZkkNj6G8VdfK/f9ToMz48ugP8nt/3FyhneqSlPXpJ2onfzYSmDwXZu+WRHSiDTPK2Q9rG7HuX2rvc+nnysUz53bogKvLvNWFX0Nrwxs1jPd/U9zo0GKV0rRST4Vl9UQjoAZp0bA73tJg=
