language: java
jdk:
- openjdk8
before_install:
- chmod +x mvnw
script: "./mvnw clean install"
notifications:
  email: rodrigocallegaldos@gmail.com
deploy:
  app: upc-202102-sw61-sale-system-1
  provider: heroku
  api_key: 
